# Generated by Django 4.1 on 2022-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50, null=True)),
                ('customerMobile', models.CharField(max_length=20, null=True)),
                ('hall', models.CharField(max_length=20, null=True)),
                ('peopleNumber', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
